### PR TITLE
[DROOLS-1247] DO NOT MERGE

### PR DESCRIPTION
**Pull request by mariofusco**

### CODE REVIEW

**Comment by manstis** [comment]
The Emperor's new codes?

**Comment by manstis** [comment]
https://en.m.wikipedia.org/wiki/The_Emperor%27s_New_Clothes

**Comment by mariofusco** [comment]
@manstis Since I developed a fix on drools in this PR https://github.com/droolsjbpm/drools/pull/861 and I think it could have a relevant impact on jbpm, I also wanted jenkins to run the jbpm test suite against it. @mswiderski suggested me to create here an empty PR with same branch name of the other PR to achieve this.

**Comment by manstis** [comment]
Sure thing... I never question your code or motives!

**Pull request closed without merging**
