### PR TITLE
DROOLS-987 - Errors in Phreak under heavy and multi threaded load

### PR DESCRIPTION
**Pull request by mswiderski**
@mariofusco here are the changes we talked about

@krisv we need to talk about this as it quite a lot change the business rule task - it makes it sync/no wait state which essentially it was anyway in v6 as we always triggered it via listener (rule flow group activated calls fireAllRules).

### CODE REVIEW

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
finally build is green, but lets try it once again just to be sure ... jenkins retest this

**Comment by mswiderski** [comment]
jenkins retest this

**Pull request merged**
