### PR TITLE
DROOLS-1073 Option to bypass start task operation in REST/JMS

### PR DESCRIPTION
**Pull request by ibek**
(cherry picked from commit 0c42014cf9b159fad2f9543749fc91044655977c)

### CODE REVIEW

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
build failure not related to the change but just in case, let's rerun the test

**Comment by ibek** [comment]
oh no, it failed again ... I tested it locally and it works fine there

**Comment by mswiderski** [comment]
+1 the failed test is a false alarm

**Comment by mswiderski** [comment]
merged into 6.4.x thanks @ibek

**Pull request closed without merging**
