### PR TITLE
Register task service instead of kie session twice

### PR DESCRIPTION
**Pull request by selrahal**

### CODE REVIEW

**Comment by mswiderski** [comment]
@selrahal do you mind adding a test for this to make sure we catch any regressions there? and jira would be good as well so we have issue tracked as well. Thanks

**Comment by selrahal** [comment]
@mswiderski updated with test

**Comment by mswiderski** [comment]
ok to test

**Comment by selrahal** [comment]
@mswiderski Can you take a look at the failure? I can't reproduce that locally :/

**Comment by psiroky** [comment]
The failure is likely not related to your changes. It is just the tests are not stable and are failing on some environments sometimes (flakey tests).

I saw that the changes contain tabs for indenting, would it be possible to change that to 4 spaces to follow our code style?

**Pull request closed without merging**
