### PR TITLE
GUVNOR-2173 - Asset Oracle: Change Impact prediction -- support for signal and global information

### PR DESCRIPTION
**Pull request by mrietveld**
@mswiderski Would you mind taking a look? 

(Or @psiroky, now that you're also working on jBPM? :D )

### CODE REVIEW

**Comment by mswiderski** [comment]
in general it looks ok, just we need to rerun the build but it seems to be required to rebase from master due to this commit https://github.com/droolsjbpm/jbpm/commit/9afa0678709b7a7aa8e3c7411ef96925ccb6dedb

@mrietveld could you please rebase?

**Comment by mrietveld** [comment]
@mswiderski Thanks, rebased. Waiting for build to complete now..

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mrietveld** [comment]
looking at tests..

**Comment by mrietveld** [comment]
jenkins retest this

**Comment by mrietveld** [comment]
***That*** (not seeing [this](https://github.com/droolsjbpm/jbpm/blob/master/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/core/Error.java#L28))  was a stupid mistake by me.. :/ Fixed!

**Comment by mrietveld** [comment]
Jenkins retest this again, please?

**Comment by mrietveld** [comment]
Jenkins retest this

**Comment by mrietveld** [comment]
The build is failling on this message, which is related to jars in the classpath (that they're corrupted, IIRC) and not related to the PR. 

```
java.lang.RuntimeException: Unable to get LastModified for ClasspathResource
	at org.drools.core.io.impl.ClassPathResource.getURL(ClassPathResource.java:173)
	at org.drools.core.io.impl.ClassPathResource.getLastModified(ClassPathResource.java:185)
	at org.drools.core.io.impl.ClassPathResource.getInputStream(ClassPathResource.java:149)
	at org.drools.compiler.kie.builder.impl.KieFileSystemImpl.write(KieFileSystemImpl.java:65)
	at org.jbpm.kie.test.util.AbstractKieServicesBaseTest.createKieJar(AbstractKieServicesBaseTest.java:198)
	at org.jbpm.kie.test.util.AbstractKieServicesBaseTest.createKieJar(AbstractKieServicesBaseTest.java:187)
	at org.jbpm.kie.services.test.DeploymentServiceTest.prepare(DeploymentServiceTest.java:72)
```

**Comment by mrietveld** [comment]
@psiroky Any tips about above? The build doesn't want to complete.. :_\

**Comment by mrietveld** [comment]
jenkins retest

**Comment by mrietveld** [comment]
and.. jenkins retest

**Comment by mrietveld** [comment]
and.. one more time, jenkins retest.. :/

**Comment by mrietveld** [comment]
Jenkins retest -- and this is the last time, I promise!

**Comment by mswiderski** [comment]
+1 to merge

**Pull request merged**
