### PR TITLE
JBPM-5084: troubleshooting function for workitem: unit test

### PR DESCRIPTION
**Pull request by bxf12315**
@mswiderski 
I create unit test for  PR :https://github.com/droolsjbpm/drools/pull/744

But, I find i just can test DefaultWorkItemManager,can not test JPAWorkItemManager.
and How to test InfinispanWorkItemManager?

### CODE REVIEW

**Comment by bxf12315** [comment]
@mswiderski 
How to test JPAWorkItemmanager?
I find the line never executed.https://github.com/droolsjbpm/jbpm/pull/461/files#diff-c8a0ebe8279172ed72b6bf171d965c9fR73

**Comment by mswiderski** [comment]
could you please move the tests to jbpm-test-coverage instead of jbpm-test as jbpm-test is only test utilities (or support test classes) and should not contain actual tests of functionality etc of jbpm itself.

your test is running currently an in memory engine only - this is driven by the constructor of JbpmJUnitBaseTestCase where you can define if the data source and persistence should be enable for not. Since you don't use any constructor explicitly it will use the defaults.
You can use @Parametrized JUnit support to make it flexible and included only in one class

**Comment by bxf12315** [comment]
@mswiderski 
I use  setupDataSource and sessionPersisence model.
https://gist.github.com/bxf12315/a8de14c2a82151f33c971bdeca237e42#file-gistfile1-txt-L28
But i find tow question:
1 code line :https://gist.github.com/bxf12315/a8de14c2a82151f33c971bdeca237e42#file-gistfile1-txt-L49
  if process throw exception , processInstance is null.
2 code line :https://gist.github.com/bxf12315/a8de14c2a82151f33c971bdeca237e42#file-gistfile1-txt-L57
  if use default model , here can get processInstance , but use  setupDataSource sessionPersisence model. also can not get processInstance.

How get a processInstance in the model?

**Comment by mswiderski** [comment]
can this be closed as new PR was opened https://github.com/droolsjbpm/jbpm/pull/466?

**Comment by bxf12315** [comment]
ok

**Pull request closed without merging**
