### PR TITLE
RHBPMS-4249, JBPM-5319 - Transaction exception for Per Process Instan…, RHBPMS-4247, JBPM-5317 - Failed to upgrade process instances in Maria

### PR DESCRIPTION
**Pull request by mswiderski**
@sutaakar do you mind taking a look and if you have a change to double check it?

this PR consists of both 
- migration sql fix - split into two sql (collect nodes to update and then update)
- weblogic transaction issue - somehow transaction manager in weblogic couldn't deal with multiple transactions within same incoming request though making it as single works properly. Due to the issue in finding the cause - very few information about the cause and not being able to debug it was better to make it as single tx, and it will make it slightly faster as well as only one tx is started.

### CODE REVIEW

**Comment by sutaakar** [comment]
changes looks good
Tried 6.5.x with weblogic transaction issue locally and it looks fixed.
Will try migration issue too.....

**Comment by sutaakar** [comment]
Migration issue looks fixed too, checked on MariaDB.

**Comment by mswiderski** [comment]
@sutaakar thanks for quick verification and review

**Comment by mswiderski** [comment]
merged manually to prevent separate commits

**Comment by manstis** [comment]
@mswiderski I assume you merged manually to *keep* separate commits; not *prevent* them!

**Comment by mswiderski** [comment]
@manstis of course, that's what happens when there are too many ideas on how to write something... I should stick to simple and not try to be smarter than...

**Pull request closed without merging**
