### PR TITLE
Fix for DROOLS-975.  Retrieving TransactionManager from factory.

### PR DESCRIPTION
**Pull request by lukenjmcd**
Use TransactionManagerFactory instead of directly instantiating JtaTransactionManager.  Also changed some references to JtaTransactionManager where TransactionManager would suffice.

### CODE REVIEW

**Comment by mrietveld** [comment]
Depends on https://github.com/droolsjbpm/drools/pull/553

**Comment by mswiderski** [comment]
ok to test

**Comment by mswiderski** [comment]
test failures are not related to the PR so +1

**Comment by mariofusco** [comment]
Merged by https://github.com/droolsjbpm/jbpm/commit/a75891365de431be7b50ea8245522f28f17b1c69

**Pull request closed without merging**
