### PR TITLE
JBPM-4768 - SQL upgrade scripts - changing SessionInfo primary key column data type fails

### PR DESCRIPTION
**Pull request by spolti**

### CODE REVIEW

**Comment by baldimir** [comment]
One thing we should be aware of is that these scripts introduce new delimiter "@", so we should modify our SQL scripts tests so they accompany this delimiter. The influenced class is here [1]. Maybe I can create separate PR for that. 

[1] https://github.com/droolsjbpm/jbpm/blob/f2ab6908ae8c2a2cd2e23fc3c6cbf6a01badb34a/jbpm-installer/src/test/java/org/jbpm/persistence/scripts/util/SQLScriptUtil.java

**Comment by mswiderski** [comment]
what's the reason to change the semi colon to at sign? Is this to allow the custom sql procedures to be defined?

**Comment by spolti** [comment]
Hi Marco, I tried for a while create a procedure using ";" as delimiter, but i some errors, when changed to @ worked. As the script worked with @ i didn't test with ;

**Comment by krisv** [comment]
Merged in master (with some additional changes):
https://github.com/droolsjbpm/jbpm/commit/b1b5c3480

**Pull request closed without merging**
