### PR TITLE
BZ-1125077 - upgrading code to default behavior in 7.x

### PR DESCRIPTION
**Pull request by mrietveld**
@mswiderski Could you take a look when you get a chance? Thanks!

### CODE REVIEW

**Comment by mswiderski** [comment]
+1 - just waiting for jenkins to run the build, thanks @mrietveld

**Comment by mswiderski** [comment]
looks like the build failed and seems to be related to this change, @mrietveld do you mind taking a quick look? Would be good to fix the build as it now fails all the time on master, thanks!

**Comment by psiroky** [comment]
Could this somehow break backwards compatibility? If so, I think we should document this in 6 -> 7 migration guide (would have to be started in kie-docs)

**Comment by mrietveld** [comment]
+1 on a backwards compatibility guide, @psiroky. I'll start a related PR.

**Comment by mrietveld** [comment]
@mswiderski updated. Feel free to rebase JBPM-4910 on this?

**Comment by mswiderski** [comment]
thanks @mrietveld will merge this and then cherry pick only JBPM-4910 from the other PR...waiting for jenkins build to complete.

**Comment by mswiderski** [comment]
+1 all good now :)

**Pull request closed without merging**
