### PR TITLE
JBPM-5541 - Case file conditional event fails other cases

### PR DESCRIPTION
**Pull request by mswiderski**
depends on https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/202

### CODE REVIEW

**Comment by mswiderski** [comment]
@krisv this is the alternative which I opt at merging rather than https://github.com/droolsjbpm/jbpm/pull/724, wdyt?

**Comment by krisv** [comment]
+1, developer has some responsibility here, we can request feedback on how to simplify this even further, but forcing the separation at engine level (as the previous PR was doing) doesn't seem ideal as it seems to introduce issues as well

**Comment by mswiderski** [comment]
depends on https://github.com/droolsjbpm/drools/pull/1072

**Comment by mswiderski** [comment]
jenkins retest this

**Pull request merged**
