### PR TITLE
JBPM-5082: Updating global realm configuration to make the users and groups management work by default on the jbpm installer.

### PR DESCRIPTION
**Pull request by romartin**

### CODE REVIEW

**Comment by mswiderski** [comment]
looks good to me, so +1 to merge

@krisv any comments from your side as you manage installer?

**Comment by mswiderski** [comment]
is this still needed for 6.4.x?

I guess we don't plan any community updates and installer is not used in product...

**Comment by romartin** [comment]
@mswiderski Thanks! mmm not sure right now, should be nice having on the community but if no updates are comming... @krisv what you dot think?

**Comment by mswiderski** [comment]
closing this one for now, if we find a need for it to be merged we can always reopen.

**Pull request closed without merging**
