### PR TITLE
BZ1240215 Create a BoundaryEvent with fluent API

### PR DESCRIPTION
**Pull request by tkobayas**
- Test case and fix. Tested only boundaryTimer case

### CODE REVIEW

**Comment by mswiderski** [comment]
@tkobayas is this complete solution? I see only timerCycle support in there or is it more for sharing idea and that needs to some more work?

**Comment by tkobayas** [comment]
Hi Maciej, sorry about the lack of explanation.

I was expecting that BoundaryEventNodeFactory.eventType() and BoundaryEventNodeFactory.setMetaData() work for general use cases. timeCycle() is a convenient/fluent method for BoundaryTimerEvent case. But yes, only one timeCycle() looks odd so I have added some more fluent methods in the new commit.

However, this is not yet complete in terms of all BoundaryEvent use cases. Actually, I tried to implement BoundaryErrorEvent use case but it would require many changes. For example, RuleFlowProcessFactory should hold org.jbpm.bpmn2.core.Definitions for error definitions so jbpm-flow will depends on jbpm-bpmn2 project. Is it the right way to go?

Probably we may merge the commit only for BoundaryEventTimer use case and file a JIRA for other BoundaryEvent use cases for future enhancement. WDYT?

**Comment by mswiderski** [comment]
sounds good to me, will merge it today (hopefully) and feel free to open another jira for further enhancement. Anyway we cannot support all possible bpmn2 constructs via fluent api I believe as it might be rather extensive work effort ... so gradually improving it might be the way to go.

Thanks Toshiya!

**Comment by mswiderski** [comment]
merged into master, thanks

**Comment by tkobayas** [comment]
Thanks Maciej,

Filed a JIRA https://issues.jboss.org/browse/JBPM-4696

**Pull request closed without merging**
