### PR TITLE
move bitronix setting to top level test to be applied to all test cases

### PR DESCRIPTION
**Pull request by mswiderski**
@psiroky here is the pr we talked about

### CODE REVIEW

**Comment by psiroky** [comment]
+1 to merge once the build is done without any related issue/test fail. I know there still may be some false negatives.

**Comment by psiroky** [comment]
The test failures are not related (most likely intermittent fails). We should fix them anyway (of course not as part of this PR) otherwise the PR builds loose their value as we will never have "green" build.

**Comment by psiroky** [comment]
We should cherry-pick this into 6.3.x as well.

**Comment by mswiderski** [comment]
done, both master and 6.3.x

**Pull request closed without merging**
