### PR TITLE
JBPM-5189 - Consider charset parameter of Content-Type when creating StringEntity

### PR DESCRIPTION
**Pull request by zcc39r**

### CODE REVIEW

**Comment by mswiderski** [comment]
could you please add a test case to https://github.com/droolsjbpm/jbpm/blob/master/jbpm-workitems/src/test/java/org/jbpm/process/workitem/rest/RestWorkItemHandlerTest.java

**Comment by mswiderski** [comment]
ok to test

**Comment by zcc39r** [comment]
Tests added.

**Comment by mswiderski** [comment]
ok to test

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
excellent work, thanks a lot for contribution @zcc39r

**Pull request merged**
