### PR TITLE
BZ-1285815 - auto claim is performed even though multiple actors are …

### PR DESCRIPTION
**Pull request by mswiderski**
…specified in HT within swimlane

### CODE REVIEW

**Comment by mrietveld** [comment]
+1

You're probably already submitting a doc PR, I'm guessing. :)

**Comment by mrietveld** [comment]
Hmm.. please double-check test failures, the same tests are not failing on master, but may be related to the parallel builds test problem.

**Comment by mswiderski** [comment]
these are still to be fixed (or removed if not possible to make them reliable) as from time to time they cause false alarms. I did execute complete test case locally to double check it did not break anything - no issues found.

**Comment by mrietveld** [comment]
Thanks! +1 for merging then.

**Pull request closed without merging**
