### PR TITLE
improve test stability

### PR DESCRIPTION
**Pull request by mswiderski**
backport of https://github.com/droolsjbpm/jbpm/pull/368 for 6.3.x

### CODE REVIEW

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by psiroky** [comment]
Test `org.jbpm.test.regression.ParallelAsyncJobsTest.testRunBasicAsync` failed three times in a row. I am not sure if it was failing before these changes, but currently it seems that the fails are not intermittent, but rather permanent.

**Comment by mswiderski** [comment]
It might be due to an issue after merge as there were some conflicts and I might not cover all things properly. Will look into it

Dnia 19.12.2015 o godz. 12:39 Petr Široký <notifications@github.com> napisał(a):

**Comment by mswiderski** [comment]
@psiroky I am really lost here... it's certainly something weird going on here... and just noticed that this test was not modified as part of this change.
It clearly checks if there are multiple executor threads running but regardless of what I use to configure it does still use just single thread:
https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbpm-pullrequests/87/testReport/org.jbpm.test.regression/ParallelAsyncJobsTest/testRunBasicAsync/

could you let me know how the build works as it seems it might be related to it. Especially parallel builds - are they in separate forked jams or share the same instance?

**Comment by mswiderski** [comment]
just noticed it does fail constantly on 6.3.x so not related to this pr ... anyway will try to do some digging why it it's failing on 6.3.x and not on master

**Comment by mswiderski** [comment]
@psiroky after 3 days of fighting I decided to ignore this test on 6.3.x. It does work well locally even with exact same maven goals and parameters as on jenkins. Tried that many times. So there is no issue with functionality itself. 
I opt at merging this in so we have more stable builds and try to find some time later on to look at this test. 
Any objections?

**Comment by mswiderski** [comment]
merged into 6.3.x

**Pull request closed without merging**
