### PR TITLE
Add revapi plugin to check public API in jbpm-services-api module

### PR DESCRIPTION
**Pull request by MarianMacik**
Hi, @mswiderski,

here is the revapi plugin configured for jbpm-services-api module. Thanks for justifications you made. Please wait for this PR droolsjbpm/droolsjbpm-build-bootstrap#303 to be merged, so we have the most up-to-date version tested.

Marian

### CODE REVIEW

**Comment by psiroky** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by MarianMacik** [comment]
I think that this can be merged now.

**Comment by psiroky** [comment]
It would be great if someone could review this. @mswiderski could you please take a look?

**Comment by MarianMacik** [comment]
@mswiderski has already provided justifications for it in my fork, so he knows about that.

**Comment by mswiderski** [comment]
@psiroky if you don't mind could you please merge when all dependencies are merged?

**Pull request merged**
