### PR TITLE
BPMSPL-295 - Higher level of automation when importing custom workItemHandlers from a service repository - update to workitem definitions impl and repository and tests

### PR DESCRIPTION
**Pull request by tsurdilo**
- added mavenDependencies, description and version to WorkDefinitionImpl
- added filtering of repository results by list of workitem definitions names
- added tests

### CODE REVIEW

**Comment by mrietveld** [comment]
Jenkins, please retest

**Comment by mrietveld** [comment]
+1 once tests complete. 

@tsurdilo Would you mind also adding some documentation about it? Maybe as a chapter (just with a short example?) here: https://github.com/droolsjbpm/kie-docs/tree/master/jbpm-asciidocs/src/main/asciidoc/DomainSpecificProcesses

**Comment by tsurdilo** [comment]
@mrietveld sure thing! I will add docs once BPMSPL-295 is completed - it spans into workbench and bpmn2 editor too and Ill update docs then for all. Is that ok?

**Comment by mrietveld** [comment]
@tsurdilo Sounds good -- thanks.

**Pull request merged**
