### PR TITLE
Move remote EJB tests to upstream.

### PR DESCRIPTION
**Pull request by rsynek**
This PR introduces testing of jbpm-services-ejb via remote access to EJBs (client-server) into the jbpm-container-test module. Existing content of jbpm-container-test has been moved to a submodule jbpm-in-container-test next to the new jbpm-remote-ejb-test module.

The jbpm-remote-ejb-test module brings in standalone testing WAR app, shared domain classes, testing KJARs and test suite itself. Supported containers are currently Wildfly10 and EAP7. Tests run length is ~5 minutes.

### CODE REVIEW

**Comment by triceo** [comment]
Are we planning to get this into 6.5.x as well?

**Comment by mswiderski** [comment]
looks good, thanks a lot @rsynek 

noticed that most of the classes are missing license headers and I believe we have a policy to include them in all source classes, though not sure how strict it is when it comes to test classes...

**Comment by rsynek** [comment]
@triceo not at this moment, but it should be possible. I need to take a look at how much effort would it be first.

**Comment by rsynek** [comment]
@mswiderski Thanks for review, please wait with merging, will include the license headers.

**Comment by rsynek** [comment]
@mswiderski license header added to hopefully all *.java files, feel free to merge.

**Comment by mswiderski** [comment]
@rsynek build failure seems to be related to this change, do you mind taking a look?

**Comment by rsynek** [comment]
@mswiderski sure, first failure solved, looking at the next one.

**Comment by rsynek** [comment]
Jenkins retest this.

**Comment by mswiderski** [comment]
@rsynek are there any other changes needed here? The query filter PR was just merged.

**Comment by rsynek** [comment]
@mswiderski  the current fail does not seem to be connected with changes from this PR. The test expects to have the nodes ordered by date and id descending https://github.com/droolsjbpm/jbpm/blob/master/jbpm-services/jbpm-services-cdi/src/test/java/org/jbpm/services/cdi/test/RuntimeDataServiceTest.java#L192, but corresponding named query `getProcessInstanceCompletedNodes` orders just by date ascending. Locally the assert sometimes passes and sometimes fails, the order in which are nodes retrieved might be non-deterministic, provided the timestamp is equal for two nodes.

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
thanks @rsynek, feel free to make the update of the query otherwise I'll add it later this/next week

**Comment by rsynek** [comment]
@mswiderski np, will take a look at fixing the query

**Comment by rsynek** [comment]
Jenkins retest this

**Comment by rsynek** [comment]
@mswiderski if you agree with the recent fix of JBPM-5431, please feel free to merge this PR.

**Pull request merged**
