### PR TITLE
Small config fixes after upgrade to IP BOM 6.0.0.CR31

### PR DESCRIPTION
**Pull request by psiroky**
Needs to be merged together with https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/116.

### CODE REVIEW

**Comment by mswiderski** [comment]
+1 looks good to me, @mrietveld any comments as this is related to query builder capabilities, I believe

**Comment by psiroky** [comment]
Just to provide a bit more info: We are now using `maven-compiler-plugin` in version 3.1 (before it was 2.6). The configuration changed a bit, so it had to be adjusted for the processor to be correctly picked up.

**Comment by mswiderski** [comment]
thanks @psiroky  for explanation. so is this ready to be merged now? I mean the upgrade of IP BOM has been done?

**Comment by psiroky** [comment]
This is ready to be merged. The IP BOM upgrade will done via https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/116, so it is needs to be merged together with this PR.

**Comment by psiroky** [comment]
I can do the merge once all the PRs have +1 (there is also one pending in dashboard-builder).

**Comment by mswiderski** [comment]
ok, then I leave that to you @psiroky , thanks

**Pull request closed without merging**
