### PR TITLE
The class org.jbpm.process.instance.event.DefaultSignalManager is not…

### PR DESCRIPTION
**Pull request by jcavieres**
There is a concurrency problem in the class org.jbpm.process.instance.event.DefaultSignalManager. 
It is not threadSafe because the variable processEventListeners is of type HashMap and because the creation of processEventListeners and eventListeners is not synchronized. This proposed change solves that problem.

### CODE REVIEW

**Comment by mswiderski** [comment]
and in what scenario this problem arise?

In general the kiesession is the "guard" of concurrency and when using command based ksession that is then secured and there is no need for any additional synchronization. Please describe the use case

**Comment by jcavieres** [comment]
Hi,
1) The proposed change is very similar to what was done here for a similar
problem:
https://issues.jboss.org/browse/DROOLS-1000

2) Answering your question, in our case it happens once a month, so it's a
possible but rare situation.
The result is 2 threads using 100% CPU each with the folowing call stack.
As you can see everything starts with a completeWorkItem call in each
thread:

"processExecutor-6374355" prio=10 tid=0x00007fe7406aa000 nid=0x161ed
runnable [0x00007fe71f1f8000]
   java.lang.Thread.State: RUNNABLE
    at java.util.HashMap.getEntry(HashMap.java:469)
    at java.util.HashMap.get(HashMap.java:421)
    at
org.jbpm.process.instance.event.DefaultSignalManager.addEventListener(DefaultSignalManager.java:55)
    at
org.jbpm.workflow.instance.impl.WorkflowProcessInstanceImpl.addEventListener(WorkflowProcessInstanceImpl.java:540)
    at
org.jbpm.workflow.instance.node.SubProcessNodeInstance.addProcessListener(SubProcessNodeInstance.java:249)
    at
org.jbpm.workflow.instance.node.SubProcessNodeInstance.internalTrigger(SubProcessNodeInstance.java:210)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.trigger(NodeInstanceImpl.java:173)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerNodeInstance(NodeInstanceImpl.java:366)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerConnection(NodeInstanceImpl.java:381)
    at
org.jbpm.workflow.instance.node.SplitInstance.executeStrategy(SplitInstance.java:117)
    at
org.jbpm.workflow.instance.node.SplitInstance.internalTrigger(SplitInstance.java:63)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.trigger(NodeInstanceImpl.java:173)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerNodeInstance(NodeInstanceImpl.java:366)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerCompleted(NodeInstanceImpl.java:325)
    at
org.jbpm.workflow.instance.node.StartNodeInstance.triggerCompleted(StartNodeInstance.java:73)
    at
org.jbpm.workflow.instance.node.StartNodeInstance.internalTrigger(StartNodeInstance.java:44)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.trigger(NodeInstanceImpl.java:173)
    at
org.jbpm.workflow.instance.node.CompositeNodeInstance.internalTrigger(CompositeNodeInstance.java:144)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.trigger(NodeInstanceImpl.java:173)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerNodeInstance(NodeInstanceImpl.java:366)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerConnection(NodeInstanceImpl.java:381)
    at
org.jbpm.workflow.instance.node.SplitInstance.executeStrategy(SplitInstance.java:117)
    at
org.jbpm.workflow.instance.node.SplitInstance.internalTrigger(SplitInstance.java:63)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.trigger(NodeInstanceImpl.java:173)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerNodeInstance(NodeInstanceImpl.java:366)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerCompleted(NodeInstanceImpl.java:325)
    at
org.jbpm.workflow.instance.impl.ExtendedNodeInstanceImpl.triggerCompleted(ExtendedNodeInstanceImpl.java:44)
    at
org.jbpm.workflow.instance.node.StateBasedNodeInstance.triggerCompleted(StateBasedNodeInstance.java:341)
    at
org.jbpm.workflow.instance.node.CompositeNodeInstance.triggerCompleted(CompositeNodeInstance.java:171)
    at
org.jbpm.workflow.instance.node.CompositeNodeInstance.nodeInstanceCompleted(CompositeNodeInstance.java:401)
    at
org.jbpm.workflow.instance.node.EndNodeInstance.internalTrigger(EndNodeInstance.java:71)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.trigger(NodeInstanceImpl.java:173)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerNodeInstance(NodeInstanceImpl.java:366)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerCompleted(NodeInstanceImpl.java:325)
    at
org.jbpm.workflow.instance.impl.ExtendedNodeInstanceImpl.triggerCompleted(ExtendedNodeInstanceImpl.java:44)
    at
org.jbpm.workflow.instance.node.StateBasedNodeInstance.triggerCompleted(StateBasedNodeInstance.java:341)
    at
org.jbpm.workflow.instance.node.StateBasedNodeInstance.triggerCompleted(StateBasedNodeInstance.java:318)
    at
org.jbpm.workflow.instance.node.WorkItemNodeInstance.triggerCompleted(WorkItemNodeInstance.java:323)
    at
org.jbpm.workflow.instance.node.WorkItemNodeInstance.workItemCompleted(WorkItemNodeInstance.java:385)
    at
org.jbpm.workflow.instance.node.WorkItemNodeInstance.signalEvent(WorkItemNodeInstance.java:361)
    at
org.jbpm.workflow.instance.impl.WorkflowProcessInstanceImpl.signalEvent(WorkflowProcessInstanceImpl.java:484)
    - locked <0x00000005f34b0e28> (a
org.jbpm.ruleflow.instance.RuleFlowProcessInstance)
    at
org.drools.core.process.instance.impl.DefaultWorkItemManager.completeWorkItem(DefaultWorkItemManager.java:132)
    at
com.zweicom.process.bpmn2.workitem.AbstractWorkItemHandler.execute(AbstractWorkItemHandler.java:312)
    at
com.zweicom.process.bpmn2.workitem.AbstractWorkItemHandler.access$000(AbstractWorkItemHandler.java:39)
    at
com.zweicom.process.bpmn2.workitem.AbstractWorkItemHandler$RunAsyncThread.run(AbstractWorkItemHandler.java:233)
    at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)

   Locked ownable synchronizers:
    - <0x00000005f34990c0> (a
java.util.concurrent.ThreadPoolExecutor$Worker)


"taskExecutor-3" prio=10 tid=0x00007fe758b70000 nid=0x1e399 runnable
[0x00007fe7295ad000]
   java.lang.Thread.State: RUNNABLE
    at java.util.HashMap.getEntry(HashMap.java:469)
    at java.util.HashMap.get(HashMap.java:421)
    at
org.jbpm.process.instance.event.DefaultSignalManager.addEventListener(DefaultSignalManager.java:55)
    at
org.jbpm.workflow.instance.impl.WorkflowProcessInstanceImpl.addEventListener(WorkflowProcessInstanceImpl.java:540)
    at
org.jbpm.workflow.instance.node.SubProcessNodeInstance.addProcessListener(SubProcessNodeInstance.java:249)
    at
org.jbpm.workflow.instance.node.SubProcessNodeInstance.internalTrigger(SubProcessNodeInstance.java:210)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.trigger(NodeInstanceImpl.java:173)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerNodeInstance(NodeInstanceImpl.java:366)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerCompleted(NodeInstanceImpl.java:325)
    at
org.jbpm.workflow.instance.impl.ExtendedNodeInstanceImpl.triggerCompleted(ExtendedNodeInstanceImpl.java:44)
    at
org.jbpm.workflow.instance.node.StateBasedNodeInstance.triggerCompleted(StateBasedNodeInstance.java:341)
    at
org.jbpm.workflow.instance.node.StateBasedNodeInstance.triggerCompleted(StateBasedNodeInstance.java:318)
    at
org.jbpm.workflow.instance.node.SubProcessNodeInstance.processInstanceCompleted(SubProcessNodeInstance.java:289)
    at
org.jbpm.workflow.instance.node.SubProcessNodeInstance.signalEvent(SubProcessNodeInstance.java:259)
    at
org.jbpm.workflow.instance.impl.WorkflowProcessInstanceImpl.signalEvent(WorkflowProcessInstanceImpl.java:490)
    - locked <0x00000005f34b11e8> (a
org.jbpm.ruleflow.instance.RuleFlowProcessInstance)
    at
org.jbpm.process.instance.event.DefaultSignalManager.internalSignalEvent(DefaultSignalManager.java:82)
    at
org.jbpm.process.instance.event.DefaultSignalManager$SignalAction.execute(DefaultSignalManager.java:181)
    at
org.drools.reteoo.common.ReteWorkingMemory.executeQueuedActionsForRete(ReteWorkingMemory.java:245)
    at
org.drools.core.impl.StatefulKnowledgeSessionImpl.flushPropagations(StatefulKnowledgeSessionImpl.java:1994)
    at
org.drools.core.impl.StatefulKnowledgeSessionImpl.executeQueuedActions(StatefulKnowledgeSessionImpl.java:1542)
    at
org.jbpm.process.instance.event.DefaultSignalManager.signalEvent(DefaultSignalManager.java:74)
    at
org.jbpm.workflow.instance.impl.WorkflowProcessInstanceImpl.setState(WorkflowProcessInstanceImpl.java:377)
    at
org.jbpm.workflow.instance.impl.WorkflowProcessInstanceImpl.setState(WorkflowProcessInstanceImpl.java:384)
    at
org.jbpm.workflow.instance.impl.WorkflowProcessInstanceImpl.nodeInstanceCompleted(WorkflowProcessInstanceImpl.java:592)
    at
org.jbpm.workflow.instance.node.EndNodeInstance.internalTrigger(EndNodeInstance.java:71)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.trigger(NodeInstanceImpl.java:173)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerNodeInstance(NodeInstanceImpl.java:366)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerCompleted(NodeInstanceImpl.java:325)
    at
org.jbpm.workflow.instance.impl.ExtendedNodeInstanceImpl.triggerCompleted(ExtendedNodeInstanceImpl.java:44)
    at
org.jbpm.workflow.instance.node.StateBasedNodeInstance.triggerCompleted(StateBasedNodeInstance.java:341)
    at
org.jbpm.workflow.instance.node.CompositeNodeInstance.triggerCompleted(CompositeNodeInstance.java:171)
    at
org.jbpm.workflow.instance.node.CompositeNodeInstance.nodeInstanceCompleted(CompositeNodeInstance.java:401)
    at
org.jbpm.workflow.instance.node.EndNodeInstance.internalTrigger(EndNodeInstance.java:71)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.trigger(NodeInstanceImpl.java:173)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerNodeInstance(NodeInstanceImpl.java:366)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerCompleted(NodeInstanceImpl.java:325)
    at
org.jbpm.workflow.instance.node.JoinInstance.triggerCompleted(JoinInstance.java:266)
    at
org.jbpm.workflow.instance.node.JoinInstance.internalTrigger(JoinInstance.java:62)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.trigger(NodeInstanceImpl.java:173)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerNodeInstance(NodeInstanceImpl.java:366)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerConnection(NodeInstanceImpl.java:381)
    at
org.jbpm.workflow.instance.node.SplitInstance.executeStrategy(SplitInstance.java:117)
    at
org.jbpm.workflow.instance.node.SplitInstance.internalTrigger(SplitInstance.java:63)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.trigger(NodeInstanceImpl.java:173)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerNodeInstance(NodeInstanceImpl.java:366)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerConnection(NodeInstanceImpl.java:381)
    at
org.jbpm.workflow.instance.node.SplitInstance.executeStrategy(SplitInstance.java:117)
    at
org.jbpm.workflow.instance.node.SplitInstance.internalTrigger(SplitInstance.java:63)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.trigger(NodeInstanceImpl.java:173)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerNodeInstance(NodeInstanceImpl.java:366)
    at
org.jbpm.workflow.instance.impl.NodeInstanceImpl.triggerCompleted(NodeInstanceImpl.java:325)
    at
org.jbpm.workflow.instance.impl.ExtendedNodeInstanceImpl.triggerCompleted(ExtendedNodeInstanceImpl.java:44)
    at
org.jbpm.workflow.instance.node.StateBasedNodeInstance.triggerCompleted(StateBasedNodeInstance.java:341)
    at
org.jbpm.workflow.instance.node.StateBasedNodeInstance.triggerCompleted(StateBasedNodeInstance.java:318)
    at
org.jbpm.workflow.instance.node.WorkItemNodeInstance.triggerCompleted(WorkItemNodeInstance.java:323)
    at
org.jbpm.workflow.instance.node.WorkItemNodeInstance.workItemCompleted(WorkItemNodeInstance.java:385)
    at
org.jbpm.workflow.instance.node.WorkItemNodeInstance.signalEvent(WorkItemNodeInstance.java:361)
    at
org.jbpm.workflow.instance.impl.WorkflowProcessInstanceImpl.signalEvent(WorkflowProcessInstanceImpl.java:484)
    - locked <0x00000005f34b13c8> (a
org.jbpm.ruleflow.instance.RuleFlowProcessInstance)
    at
org.drools.core.process.instance.impl.DefaultWorkItemManager.completeWorkItem(DefaultWorkItemManager.java:132)
    at
com.zweicom.runtime.thread.ZwessionListenerThreadImpl.runProcessRule(ZwessionListenerThreadImpl.java:319)
    at
com.zweicom.runtime.thread.ZwessionListenerThreadImpl.runProcess(ZwessionListenerThreadImpl.java:134)
    at
com.zweicom.runtime.thread.ZwessionListenerThreadImpl.runProcess(ZwessionListenerThreadImpl.java:31)
    at
com.zweicom.runtime.thread.AbstractZwessionThread.run(AbstractZwessionThread.java:67)
    at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)

   Locked ownable synchronizers:
    - <0x00000005b61ff1f0> (a
java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by mswiderski** [comment]
so you don't use persistence with processes at all?

**Comment by jcavieres** [comment]
No, we don't

Regards

**Comment by mswiderski** [comment]
ok, thanks for the details, now it's clear

ok to test

**Comment by mswiderski** [comment]
ok to test

**Comment by mswiderski** [comment]
test failures are certainly related to this change, can you please have a look @jcavieres ?

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by jcavieres** [comment]
@mswiderski It's OK now

**Comment by mswiderski** [comment]
thanks @jcavieres though I just noticed that this PR targets 6.5.x branch which is not frozen as 6.5.0 was released so to merge this we would have to move this PR to master.

what would be good as well is to create jira for it so it has a reference why it was done.

**Comment by livthomas** [comment]
@jcavieres, please, squash your commits on `6.5.x` branch to a single commit, cherry-pick it to your copy of `master` branch and send a new pull-request. There are too many changes between the two branches since they were split many months ago.

**Comment by jcavieres** [comment]
I had to create a new pull request in order to change to master
https://github.com/droolsjbpm/jbpm/pull/670

Regards
JCS

**Pull request closed without merging**
