### PR TITLE
Modify DefaultSignalManager for concurrency

### PR DESCRIPTION
**Pull request by jcavieres**
There is a concurrency problem in the class org.jbpm.process.instance.event.DefaultSignalManager.
It is not threadSafe because the variable processEventListeners is of type HashMap and because the creation of processEventListeners and eventListeners is not synchronized. This proposed change solves that problem.

### CODE REVIEW

**Comment by jcavieres** [comment]
@mswiderski please give "ok to test" to this new PR

**Comment by mswiderski** [comment]
ok to test

**Comment by mswiderski** [comment]
@jcavieres can you open jira and update commit message so we have the reference?

**Comment by jcavieres** [comment]
Done
https://issues.jboss.org/browse/JBPM-5400

**Comment by mswiderski** [comment]
merged manually with https://github.com/droolsjbpm/jbpm/commit/69057f7e9e3a421ce880e774387bb1b932c45608

thanks @jcavieres

**Pull request closed without merging**
