### PR TITLE
BZ-1276039 upgrade script (bpms-6.0-to-6.1.sql): null value in column…

### PR DESCRIPTION
**Pull request by lazarotti**
… id violates not-null constraint

### CODE REVIEW

**Comment by lazarotti** [comment]
The BZ was opened about Postgres, but certainly Oracle should has the same behavior. I do not have an Oracle instance set but the fix in this PR seems enough. For Postgres I've tested and it is now working.

**Comment by psiroky** [comment]
ok to test

**Comment by mswiderski** [comment]
@baldimir do we have tests for these upgrade scripts for postgres and oracle? If so I was wondering how this could work before.

In general this change looks good to me so +1

**Comment by baldimir** [comment]
@mswiderski Yes, I ran the tests also on Oracle and Postgres. You're right that this shouldn't work. I think that the tests passed because the majority of tables were empty when running the scripts, so the insert statement inserted nothing so no PK constraint was violated. We should add some more basic data to the tests. Especially Task data, because I see that in many cases values from that table are selected and inserted into other tables.

**Comment by mrietveld** [comment]
@baldimir +1 on filling the tables beforehand, good catch.

**Comment by krisv** [comment]
Merged (with some other improvements)

**Pull request closed without merging**
