### PR TITLE
JBPM-4880 - Create an artifact with the DDL (SQL) files needed for different database schema's

### PR DESCRIPTION
**Pull request by mrietveld**
It seems to me like this would be useful? 

@dvirgiln We talked briefly about this in september, I think?

### CODE REVIEW

**Comment by mswiderski** [comment]
Marion, can you elaborate more on what this should do? I looked at jira but didn't find details.... thanks

**Comment by manstis** [comment]
Is it the weekend already? I thought Marco preserved the use of "Marion"
until he was more relaxed ;-)

Marion, can you elaborate more on what this should do? I looked at jira but
didn't find details.... thanks

—
Reply to this email directly or view it on GitHub
<https://github.com/droolsjbpm/jbpm/pull/366#issuecomment-164927072>.

**Comment by mswiderski** [comment]
that's just my too fat fingers trying to type late evening... it should be Marco of course, sorry for that :)

**Comment by mrietveld** [comment]
I stuffed Marco in the closet for bad behavior. I'll let him out later after I do all the fun work. 

Marco talked with David Virgil Naranjo (of Fuse/Switchyard fame) in September about the fact that when Fuse does integration tests (with our stuff), it would be nice if they could just grab the DDL scripts to make the db schema for their tests. I believe it's also useful for them as part of their setup in the product/project. 

Does that make sense?

**Comment by mswiderski** [comment]
all makes perfect sense, thanks

+1

**Pull request closed without merging**
