### PR TITLE
Fixes after JPA 2.0 to 2.1 upgrade

### PR DESCRIPTION
**Pull request by psiroky**
Please don't merge yet. All the IP BOM 7.0.0.CR5 PRs need to be merged together.

### CODE REVIEW

**Comment by psiroky** [comment]
@mswiderski thanks a lot for the additional fixes!

**Comment by mswiderski** [comment]
what are the plans for this JPA 2.1 upgrade? Can we make this anytime soon to avoid this PR to become stale/out dated?

**Comment by psiroky** [comment]
I would very much like to do this asap, but there are still some tests failing in drools and droolsjbpm-integration repos. I am planning to look at those once I find some time.

**Comment by psiroky** [comment]
@mswiderski could you please approve the PR if everything is OK (just for the record)?

**Comment by mswiderski** [comment]
+1 to merge

**Pull request merged**
