### PR TITLE
JBPM-5296 - Cleaning up human-task and removing deprecated code

### PR DESCRIPTION
**Pull request by MarianMacik**
Hi, @mswiderski,

here is the PR for [JBPM-5296](https://issues.jboss.org/browse/JBPM-5296).

I have added one test, SynchronizedTaskServiceTest.java as Marco did it too. I have also added [one method](https://github.com/droolsjbpm/jbpm/compare/master...MarianMacik:JBPM-5296?expand=1#diff-d62dd9e86f9a58a0a620445837264af5R199) which Marco added as well although I am not really sure if it was needed as a bugfix or something else.

PR set:
#725 
droolsjbpm/droolsjbpm-knowledge#199

Thanks,

Marian

### CODE REVIEW

**Comment by mswiderski** [comment]
@MarianMacik overall looks good though I'd remove the SynchronizedTaskServiceTest as it does not really belong here - I mean to this jira and not sure what was the purpose of this test either.

**Comment by MarianMacik** [comment]
@mswiderski SynchronizedTaskServiceTest has been removed.

**Comment by MarianMacik** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
thanks @MarianMacik

**Pull request merged**
