### PR TITLE
HumanTaskServicesBaseTest: use null jurnal for bitronix to avoid inte…

### PR DESCRIPTION
**Pull request by psiroky**
…rruptep thread destroying transaction manager when using default disc journal

### CODE REVIEW

**Comment by psiroky** [comment]
Please cherry-pick this into 6.3.x as well, if accepted.

**Comment by mrietveld** [comment]
Looks fine -- although I don't know anything about the problem. Could you explain what the problem is? 

If you could also add it to the persistence test classes in drools-persistence-jpa, that would also be nice -- if it's applicable there. 

Thanks.

**Comment by psiroky** [comment]
TBH I don't really know that much about this. I just copied the changes @mswiderski did here https://github.com/droolsjbpm/jbpm/commit/ae6c2de28c231893fe5c270d72b584d624338fad (after checking with him). So this or may not be applicable to other tests (don't know).

**Comment by mswiderski** [comment]
in general for test purpose we can switch all tests to use NULL journal instead of disc one which is fragile to thread interruption. @psiroky would you mind extend this PR to include others as well?

**Comment by psiroky** [comment]
@mswiderski what others do you mean? All the top-level/abstract test classes?

**Comment by mswiderski** [comment]
yes, all base classes for modules starting at jbpm-persistence-jpa and up in maven module hierarchy

**Comment by psiroky** [comment]
Ouch. That will likely take more than few minutes (at least to me). I can take a look at that, but now sure when.

**Comment by mswiderski** [comment]
no worries, whoever gets into this earlier then will do it

**Comment by mswiderski** [comment]
closing this one as #314 has been merged, thanks @psiroky

**Pull request closed without merging**
