### PR TITLE
JBPM-4147 Able to use 'Task Variables' as expressions in Task properties

### PR DESCRIPTION
**Pull request by baldimir**
Modified existing test so it tests variables from issue description + new test.

### CODE REVIEW

**Comment by mswiderski** [comment]
the sessionId works fine when it comes to task variables but it is not loaded by queries such as tasks assigned as potential owners and thus it's not set on TaskSummary. You would need to load the actual Task instance instead of summary to assert on session id. The reason it is not loaded is due to session id is not relevant in most of the cases.

**Comment by baldimir** [comment]
Ok, thanks for help.. will do that.

**Comment by mswiderski** [comment]
shall we keep this pr open for the changes or?

**Comment by baldimir** [comment]
Yes please, I will write a comment when it is done.

**Comment by baldimir** [comment]
Ok now I think there's all I wanted to add.

**Comment by mswiderski** [comment]
commits squashed and merged into master, thanks @baldimir

**Pull request closed without merging**
