### PR TITLE
Proposed fix for [DROOLS-1364]

### PR DESCRIPTION
**Pull request by eliasisrael**
Proxy KieSession objects in InMemorySessionFactory so that they can
be removed from the internal sessions collection on dispose/destroy

### CODE REVIEW

**Comment by eliasisrael** [comment]
Please note the second commit, which fixes a small issue with the original proposal.

**Comment by mswiderski** [comment]
I'd prefer to avoid any kind of proxies and instead extend the SessionFactory interface to provide method to remove the ksession instead.

**Comment by eliasisrael** [comment]
I understand your reasoning on this and probably would have approached it in a similar fashion except that the code included a request for a proxy, and it would have been a much bigger change to hook into a listener somewhere (which, right now, I'm not even sure exists for the needed event).

**Comment by mswiderski** [comment]
closing as this should be addressed differently and for the case describe din DROOLS-1364 - runtime manager should not be used

**Pull request closed without merging**
