### PR TITLE
[6.5.x] Fix compilation errors after changes in KIE API (DROOLS-1275)

### PR DESCRIPTION
**Pull request by livthomas**
I have fixed compilation problems caused by [this commit](https://github.com/droolsjbpm/droolsjbpm-knowledge/commit/78002f726ef8dca62a3252597619965e239b3f0e).

### CODE REVIEW

**Comment by mswiderski** [comment]
@livthomas I actually remove this as it's no longer used and to avoid too many issues with this sort of changes ... https://github.com/droolsjbpm/jbpm/pull/572

**Comment by livthomas** [comment]
Sure, I have just noticed that. We can close this one.

**Comment by manstis** [comment]
6.5.x PRs are failing due to either this PR not being merged or changes elsewhere. For example see https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-common-pullrequests-6.x/145/console..  could somebody please investigate?

**Comment by mswiderski** [comment]
@manstis just merged #572 so the build should be back to normal

**Pull request closed without merging**
