### PR TITLE
JBPM-4604 - Added possibility to give node mapping for process instance migration by node names

### PR DESCRIPTION
**Pull request by jomarko**
Added possibility to give node mapping for process instance migration by node names.

### CODE REVIEW

**Comment by mswiderski** [comment]
@jomarko do you mind dropping a jira for it and then update commit message? Would be great to have a test case for that too, see this one [1] as it might be good to extend it. Once that is in place I'll merge it.

[1] https://github.com/droolsjbpm/jbpm/blob/master/jbpm-test/src/test/java/org/jbpm/test/persistence/migration/ProcessInstanceMigrationTest.java

**Comment by jomarko** [comment]
@mswiderski I do not mind dropping a jira for it. It is my first PR to this project, so I was not sure about workflow. Who should create jira me or you? I will add testcase in the near future.

**Comment by mswiderski** [comment]
feel free to drop jira - it's good to see contributors coming up with jiras and fixes directly :) thanks a lot!

**Comment by jomarko** [comment]
PR is not complete yet, don't resolved situations of mapping inner nodes

**Comment by jomarko** [comment]
@mswiderski I thnik that my extension which transform node name to node id is correct, but added test method testProcessInstanceMigrationExplicit() doesn't pass. I think it ilustrates what is mentioned in BZ https://bugzilla.redhat.com/show_bug.cgi?id=1211177 . 

In testProcessInstanceMigrationExplicit() I map two UserTasks. But both have different node names and different actors. I want to migrate old process instance in moment, when is active (UserTask):(ForJohn). I migrate process instance successfully == process id is changed. But if I check what is active node now, I will still obtain (UserTask):(ForJohn) not desired (UserTask):(ForBill).

**Comment by jomarko** [comment]
I am done. Tests have passed.

**Comment by Salaboy** [comment]
This is a really useful contribution! Thanks a lot. I will let @mswiderski to merge this one

**Comment by psiroky** [comment]
@jomarko could you please remove the tabs for indentation and use 4 spaces instead? (or @mswiderski please make sure to remove the the tabs when merging)

**Comment by jomarko** [comment]
Used 4 spaces for tabs.

**Comment by mswiderski** [comment]
I am about to merge that in

**Comment by mswiderski** [comment]
merged into master, thanks @jomarko

**Pull request closed without merging**
