### PR TITLE
RHBPMS-4106: [GSS](6.3.z) A ClassNotFound exception is shown while a …

### PR DESCRIPTION
**Pull request by lazarotti**
…Service task is being executed

### CODE REVIEW

**Comment by psiroky** [comment]
ok to test

**Comment by psiroky** [comment]
Thanks @lazarotti. Would it be possible to include a test as well?

FYI: if you accept the invitation to droolsjbpm github org. unit, the PR builds will be automatically executed for your PRs.

**Comment by lazarotti** [comment]
Hi Petr - I really tried create an unit test for this but the bug depends on Classloader isolation and I was not able to create a test for this or even mock the scenario. I tried creating a custom classloader but I was stuck in isolating the class for the other parts of the scenario. If there is any test related to classloader issues let me know to take a look as basis.

**Comment by lazarotti** [comment]
About the Jenkins failure, I don't think it is related to this PR.

**Comment by mswiderski** [comment]
is this only 6.4.x branch related or it requires back ports?

**Comment by lazarotti** [comment]
Also forward port Maciej. Sorry, I add it as upstream to product 6.4.x and this is why the PR was just to 6.4.x. Should I open a new PR to other branches ?

**Comment by mswiderski** [comment]
if you could open these that would be great, thanks

**Comment by mswiderski** [comment]
@lazarotti I see that that jira does not have acks so I guess we need to wait with it before it gets all approvals.

**Comment by lazarotti** [comment]
The PRs for 6.5.x and master are:
https://github.com/droolsjbpm/jbpm/pull/516
https://github.com/droolsjbpm/jbpm/pull/517

Feel free to revert the 6.4.x commit to wait until the acks if necessary. Cheers

**Comment by mswiderski** [comment]
thanks @lazarotti closing these PRs as they are replaced with other that includes test case on top of your fix - https://github.com/droolsjbpm/jbpm/pull/521

**Pull request closed without merging**
