### PR TITLE
JBPM-5231: refactored adding errors in RuleFlowProcessValidator

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by mrietveld** [comment]
+1 Nice work!

Nice use of the `String.format(..)` method.

**Comment by mrietveld** [comment]
Retracting +1 -- @jomarko wants to improve this a little more, so I'm waiting for him to update the PR.

**Comment by mrietveld** [comment]
+1 Please merge when tests complete.

**Comment by mswiderski** [comment]
@jomarko one test seems to be related to this PR https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jbpm-pullrequests-6.x/71/testReport/junit/org.jbpm.ruleflow.core.validation/RuleFlowProcessValidatorTest/testAddErrorMessage/ do you mind taking a look?

**Comment by jomarko** [comment]
@mswiderski it should be green now.

**Pull request merged**
