### PR TITLE
ProcessInstanceWithCustomVarsQueryMapper ignores the column mapping -…

### PR DESCRIPTION
**Pull request by btison**
… fix

### CODE REVIEW

**Comment by mrietveld** [comment]
+1 Normally, a test would also be nice -- but this is a pretty straightforward fix, so it's not necessary. 

Thanks for catching this, @btison!

@mswiderski or @psiroky, would you mind merging?

**Comment by psiroky** [comment]
ok to test

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
certainly +1, thanks @btison

**Pull request merged**
