### PR TITLE
JBPM-5147: Provide a JPA Work Item Handler

### PR DESCRIPTION
**Pull request by jesuino**
JBPM-5147: Provide a JPA Work Item Handler

### CODE REVIEW

**Comment by jesuino** [comment]
Hope this is correct this time, @mswiderski  :)

**Comment by mswiderski** [comment]
@jesuino looks nice and clean now, thanks. 

One thing though, looks like the handler is not thread safe as it keeps entity manager open across invocations of the executeWorkItem method. Entity manager is not thread safe thus it should not be shared. Could you change it so entity manager is created and then closed (but not cleared) within executeWorkItem method?

**Comment by psiroky** [comment]
Sorry for nit-picking, but would it be possible to reformat the code to use spaces instead of tabs ?(to be consistent with the rest of the codebase)

**Comment by jesuino** [comment]
Hello,

Thanks for both comments.

I am modifying the tests. When I close the em, it detach the entities, which makes most part of the current test obsolete. 

Sorry @psiroky  - Unfortunately my IDE configuration did not correctly replace the TAB for spaces. I will update all the Java source files.

**Pull request closed without merging**
