### PR TITLE
GUVNOR-2173 - alternative way to collect reusable processes reference…

### PR DESCRIPTION
**Pull request by mswiderski**
…d by name

Marco, here is an alternative way to look up reusable processes that are referenced by name to avoid using KieContainer in buildProcessDefinition method of the DefinitionService.

Just an idea to look at to see if we gain something with it

### CODE REVIEW

**Comment by mrietveld** [comment]
Maciej, I'm fairly sure that this doesn't work. However, I will take a look at it and write tests to test the cases that I'm thinking of. 

Thanks!

**Comment by mswiderski** [comment]
Marco, any update on this?

**Comment by mrietveld** [comment]
@mswiderski Haven't forgotten this -- and it also needs to be done before the end of this week. :/ Will get it done!

**Comment by mswiderski** [comment]
@mrietveld shall we still have it here or just close it?

**Comment by mrietveld** [comment]
I'm currently working on this -- I'll close it at the end of this week.

**Comment by mswiderski** [comment]
this PR is not more relevant so closing

**Pull request closed without merging**
