### PR TITLE
JBPM-5296 - Cleaning up human-task and removing deprecated code

### PR DESCRIPTION
**Pull request by mrietveld**
PR set: 
- https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/162
- https://github.com/droolsjbpm/jbpm/pull/562
- https://github.com/droolsjbpm/droolsjbpm-integration/pull/609

### CODE REVIEW

**Comment by mrietveld** [comment]
Jenkins, please retest (`SingletonRuntimeManagerTest.testInterceptorAfterRollback` succeeds locally -- seems like a false negative?)

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
+1 to merge once build is green

**Comment by manstis** [comment]
Jenkins please retest this.

**Pull request closed without merging**
