### PR TITLE
JBPM-5071 - Migrate InitiatorProviderProcessListener from workbench i…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…nto jbpm-kie-services

Refactored/shared common code between InitiatorProviderProcessListener and IdentityProviderAwareProcessListener

### CODE REVIEW

**Comment by mswiderski** [comment]
@cristianonicolai can we simply merge these two listeners into one as they do pretty much the same - set user name of logged in user as process variable/meta data.

Would be good to have a test within process context as well, if possible

**Comment by cristianonicolai** [comment]
@mswiderski merged both listeners into a single one. The side affect of that is IdentityProviderAwareProcessListener is registered by default into the ksession. I guess we're ok with that?

Another point is that after this change, some tests started to fail because `getProcessInstancesByVariableNameAndValue` wasn't taking into account the specific variable when checking the max id. That's why the change on `Servicesorm.xml`

**Comment by mswiderski** [comment]
+1 though can't see whats the reason of build failure so let's retest

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
looks like test failures are related to this pr, @cristianonicolai do you mind taking a look?

**Comment by mswiderski** [comment]
Thanks @cristianonicolai

**Pull request merged**
