### PR TITLE
JBPM-5320

### PR DESCRIPTION
**Pull request by krisv**

### CODE REVIEW

**Comment by mswiderski** [comment]
looks good, just to squash commits with complete commit message and it's good to be merged, once jenkins finally wakes up ;)

+1

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by krisv** [comment]
jenkins retest this

**Comment by mswiderski** [comment]
@krisv do you mind squashing these commits?

**Comment by mswiderski** [comment]
jenkins retest this

**Pull request merged**
