### PR TITLE
JBPM-5283 - Remove actual owner from roles allowed to activate tasks

### PR DESCRIPTION
**Pull request by livthomas**
I have removed unnecessary permission from `operations-dsl.mvel`.

### CODE REVIEW

**Comment by mrietveld** [comment]
Please hold off on merging this -- while what Tomas is saying makes sense with regards to the spec, I think that the code-level interpretation of "Actual owner" may not match that (and may in some cases be the initiator?). I'd like to double check that today.

**Comment by livthomas** [comment]
@mrietveld, thanks for looking at this. I ran into it when I was verifying the documentation and after a short discussion with @mswiderski decided to remove it. But I have not checked any internal interpretation of **_Actual owner_** so there is a chance it is done this way on purpose and might cause some problems. If this is a wrong step, we should also see it on failing tests.

**Comment by livthomas** [comment]
It seems that there are no related test failures. Failing `ConcurrentHumanTaskTest` is passing on my machine. It would be nice if Jenkins can retest this.

**Comment by mrietveld** [comment]
@livthomas Thanks for the additional info. 

+1

**Comment by mswiderski** [comment]
thanks guys @livthomas @mrietveld

**Pull request merged**
