### PR TITLE
SQLGrammarException reproducer

### PR DESCRIPTION
**Pull request by sutaakar**
Reproducer using PostgreSQL 9.4.

How to run it:
Start PostgreSQL, for example using Docker:
docker run --name postgres -e POSTGRES_PASSWORD=jbpm -e POSTGRES_USER=jbpm -e POSTGRES_DB=jbpm -p 5432:5432 -d postgres:9.4

Start tests using EAP6.4:
mvn clean install -Dcontainer.profile=eap64 -Deap64.download.url=....

There will be 6 test failures with same stacktrace.

### CODE REVIEW

**Comment by mswiderski** [comment]
@sutaakar have you see this: https://github.com/droolsjbpm/jbpm/pull/765 if you don't mind trying it out to see if that fixes the issue would be great?

**Comment by sutaakar** [comment]
@mswiderski Will try it

**Comment by sutaakar** [comment]
Looks good, if I apply that https://github.com/droolsjbpm/jbpm/pull/765 then all the tests pass

**Comment by mswiderski** [comment]
@sutaakar do you think we should still merge this one of #765 is enough?

**Comment by sutaakar** [comment]
@mswiderski No, this is just a reproducer - configuration for PostgreSQL, should be closed when we dn't need it any more.

**Comment by mswiderski** [comment]
ok, thanks, then I close it as I merged the #765 already

**Comment by sutaakar** [comment]
@mswiderski Just don't forget to cherrypick it to 6.5.x to have it in latest patch

**Comment by mswiderski** [comment]
so is this 6.5.x related to and not only master?

**Comment by sutaakar** [comment]
@mswiderski Yes, see RHBPMS-4638

**Pull request closed without merging**
